spring:
  console:
    enabled: true
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem;NON_KEYWORDS=user
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update