server:
  port: 8800
  devtools:
    add-properties: true

spring:
  banner: off
  datasource:
    url: jdbc:mysql://localhost:3306/khatabook_db?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

  application: General-Khatabook

#logging.level.org.springframework=info
#spring.messages.basename=messages


logging:
  level:
    org:
      springframework: info


console:
  enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    sho-details: always
